"""empty message

Revision ID: 0143ef760162
Revises: 765f6cf03939
Create Date: 2023-04-11 10:31:32.404837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0143ef760162'
down_revision = '765f6cf03939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('disease_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('symptoms', sa.String(length=500), nullable=True),
    sa.Column('treatment', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('disease_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diseases')
    # ### end Alembic commands ###
