"""empty message

Revision ID: 03792ff9ad27
Revises: 7f576539db1d
Create Date: 2023-04-02 14:29:27.179577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03792ff9ad27'
down_revision = '7f576539db1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Medical Centres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geotag', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Medical Centres', schema=None) as batch_op:
        batch_op.drop_column('contact_number')
        batch_op.drop_column('geotag')

    # ### end Alembic commands ###
