"""empty message

Revision ID: 06a46c42bf20
Revises: 67b061303140
Create Date: 2023-04-09 10:51:49.386342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a46c42bf20'
down_revision = '67b061303140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_centres',
    sa.Column('centre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('geotag', sa.String(length=200), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('contact_number2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('centre_id')
    )
    op.create_table('emergency contact',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('existing conditions',
    sa.Column('condition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('recordings',
    sa.Column('recording_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recording', sa.String(length=200), nullable=True),
    sa.Column('reading', sa.String(length=200), nullable=True),
    sa.Column('date_recorded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('recording_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recordings')
    op.drop_table('existing conditions')
    op.drop_table('emergency contact')
    op.drop_table('medical_centres')
    # ### end Alembic commands ###
