"""empty message

Revision ID: 0d30b090d824
Revises: 69b6bae21cd2
Create Date: 2023-04-02 14:15:42.280755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d30b090d824'
down_revision = '69b6bae21cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Medical Centres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geotag', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Medical Centres', schema=None) as batch_op:
        batch_op.drop_column('geotag')

    # ### end Alembic commands ###
