"""empty message

Revision ID: 1a31bb3c691e
Revises: fa6e267ec465
Create Date: 2023-05-16 08:51:18.092776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a31bb3c691e'
down_revision = 'fa6e267ec465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disease_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_column('disease_id')

    # ### end Alembic commands ###
