"""empty message

Revision ID: 25bbb854513b
Revises: 43212e92636f
Create Date: 2023-04-18 00:36:45.916498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25bbb854513b'
down_revision = '43212e92636f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recordings')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('Recordings',
    sa.Column('recording_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recording', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('reading', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('date_recorded', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='Recordings_ibfk_1'),
    sa.PrimaryKeyConstraint('recording_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
