"""empty message

Revision ID: 737d11954b0c
Revises: 1a31bb3c691e
Create Date: 2023-05-18 02:22:08.425791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737d11954b0c'
down_revision = '1a31bb3c691e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likelihood', sa.Float(precision=10, asdecimal=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_column('likelihood')

    # ### end Alembic commands ###
