"""empty message

Revision ID: 7f576539db1d
Revises: 0d30b090d824
Create Date: 2023-04-02 14:19:48.832905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f576539db1d'
down_revision = '0d30b090d824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Emergency Contact', schema=None) as batch_op:
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('Medical Centres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Medical Centres', schema=None) as batch_op:
        batch_op.drop_column('contact_number')

    with op.batch_alter_table('Emergency Contact', schema=None) as batch_op:
        batch_op.alter_column('contact_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
