"""empty message

Revision ID: a2e82a2e74e4
Revises: c485b7952348
Create Date: 2023-04-02 16:39:06.690960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e82a2e74e4'
down_revision = 'c485b7952348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Emergency Contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(), nullable=True))
        batch_op.drop_column('contact_num')

    with op.batch_alter_table('Medical Centres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number2', sa.String(), nullable=True))
        batch_op.alter_column('contact_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Medical Centres', schema=None) as batch_op:
        batch_op.alter_column('contact_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('contact_number2')

    with op.batch_alter_table('Emergency Contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_num', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
