"""empty message

Revision ID: dc5e267f46aa
Revises: 
Create Date: 2023-03-26 19:02:02.964546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5e267f46aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Emergency Contact',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('contact_number', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('Existing Conditions',
    sa.Column('condition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('Medical Centres',
    sa.Column('centre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('centre_id')
    )
    op.create_table('Recordings',
    sa.Column('recording_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recording', sa.String(length=200), nullable=True),
    sa.Column('reading', sa.String(length=200), nullable=True),
    sa.Column('date_recorded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('recording_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Recordings')
    op.drop_table('Medical Centres')
    op.drop_table('Existing Conditions')
    op.drop_table('Emergency Contact')
    # ### end Alembic commands ###
