"""empty message

Revision ID: ee0a610eac4f
Revises: 0143ef760162
Create Date: 2023-04-17 18:52:37.225239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0a610eac4f'
down_revision = '0143ef760162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=3000), nullable=True))
        batch_op.add_column(sa.Column('causes', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_column('causes')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
