"""empty message

Revision ID: f0b683e39cba
Revises: 34571c6de8db
Create Date: 2023-04-09 10:51:00.184129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0b683e39cba'
down_revision = '34571c6de8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Existing Conditions')
    op.drop_table('Recordings')
    op.drop_table('Emergency Contact')
    op.drop_table('Medical Centres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Medical Centres',
    sa.Column('centre_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Medical Centres_centre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('geotag', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_number2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('centre_id', name='Medical Centres_pkey')
    )
    op.create_table('Emergency Contact',
    sa.Column('contact_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Emergency Contact_contact_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('contact', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='Emergency Contact_user_id_fkey'),
    sa.PrimaryKeyConstraint('contact_id', name='Emergency Contact_pkey')
    )
    op.create_table('Recordings',
    sa.Column('recording_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Recordings_recording_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('recording', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('reading', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('date_recorded', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='Recordings_user_id_fkey'),
    sa.PrimaryKeyConstraint('recording_id', name='Recordings_pkey')
    )
    op.create_table('Existing Conditions',
    sa.Column('condition_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Existing Conditions_condition_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='Existing Conditions_user_id_fkey'),
    sa.PrimaryKeyConstraint('condition_id', name='Existing Conditions_pkey')
    )
    # ### end Alembic commands ###
