"""empty message

Revision ID: fa6e267ec465
Revises: 25bbb854513b
Create Date: 2023-05-16 08:50:31.652276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6e267ec465'
down_revision = '25bbb854513b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency contact', schema=None) as batch_op:
        batch_op.drop_constraint('emergency contact_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('existing conditions', schema=None) as batch_op:
        batch_op.drop_constraint('existing conditions_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_constraint('recordings_user_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.create_foreign_key('recordings_user_id_fkey', 'user', ['user_id'], ['user_id'])

    with op.batch_alter_table('existing conditions', schema=None) as batch_op:
        batch_op.create_foreign_key('existing conditions_user_id_fkey', 'user', ['user_id'], ['user_id'])

    with op.batch_alter_table('emergency contact', schema=None) as batch_op:
        batch_op.create_foreign_key('emergency contact_user_id_fkey', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
